### ISSUE TITLE
compile on ubuntu 14.10

### ISSUE THREAD

**Issue by Qu-Bit** [oNaiPs/netEditor#1]
tried as title suggests
it is _not straightforward_.

this was written on/for mac environment ?
-> **should be noted** somewhere.
- plugin compile has to be done separately
  - there is an include path issue to be fixed. the plugins will look for the headers in the created directory `netEditor`.
  - only the example plugins will compile

**Comment by Qu-Bit** [comment]
fixing the paths according to recent renaming of directories
makes build possible with QT creator
pushing changes to my fork

**Comment by oNaiPs** [comment]
@Qu-Bit thanks we are accepting pull requests / collaboration if you're interested
